#pragma config(Sensor, S1,     ButtonLeft,     sensorEV3_Touch)
#pragma config(Sensor, S4,     ButtonRight,    sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int lop = 1;
	while lop > 4;
	{
		if(lop < 4)
		{
			motor(motorB) = 50;
			motor(motorC) = 50;
			wait1Msec(1000);

		}
		if(SensorValue(ButtonLeft) == 1)
		{
			motor(motorC) = -100;
			motor(motorB) = 100;
			wait1Msec(300);
		}
		else
		{
			motor(motorB) = -100;
			motor(motorC) = 100;
			wait1Msec(300);
		}
		lop = lop + 1;
	}
}
