#pragma config(Sensor, S1,     ButtonLeft,     sensorEV3_Touch)
#pragma config(Sensor, S4,     ButtonRight,    sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)
	{
		int speedleft = 0;
		int speedright = 20;
		int time = 1000;
		int wfta = 0

		// these are variables

		while((SensorValue(ButtonLeft) == 0 && speedleft <= 100))
			{
				motor(motorB) = speedleft + 40;
				motor(motorC) = speedright + 50;
				wait1Msec(time);

				speedleft = speedleft + 3;
				speedright = speedright + 2;
				time = time + 500;

				//this is spiraling
			}

		wfta = 0

		while(SensorValue(ButtonLeft) == 1 || SensorValue(ButtonRight)== 1)
		{
			motor(motorB) = -40;
			motor(motorC) = -70;
			wait1Msec(1000);

			motor(motorB) = 60;
			motor(motorC) = 70;
			wait1Msec(1900);
			resetMotorEncoder(motorB);
			resetMotorEncoder(motorC);

			//This is wallfollowing

			wfta = wfta + 1

			if(wfta == 5 && SensorValue(ButtonLeft) == 1)
			{
				motor[motorB] = -100;
				motor[motorC] = -100;
				wait1Msec(500);

				motor[motorB] = -100;
				motor[motorC] = 100;
				wait1Msec(595);

				motor[motorB] = 100;
				motor[motorC] = 100;
				wait1Msec(2000);

				//This is the attempt of turning away from the wall


			}

		}
	}

}
